// Generates a `Workora` wrapper script under ~/.Workora/bin and injects it into the spawned agent's PATH.
// Agents call `Workora ...` from their shell/bash tool → routed to this repo's CLI.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { binDir } from "../paths.js";

export function ensureWorkoraBin(): string {
  const dir = binDir();
  fs.mkdirSync(dir, { recursive: true });

  const here = path.dirname(fileURLToPath(import.meta.url)); // repo: .../src/daemon · bundled: .../dist
  // Bundled/npm mode (@Workora/daemon): the agent CLI ships as a sibling bundle next to the daemon and
  // runs directly with node — there's no repo source or tsx on disk. Repo mode: run the TS source via tsx.
  const bundledCli = path.join(here, "agent-cli.mjs");
  let runner: string[], cliPath: string; // runner is argv-shaped so multi-word runners ("npx tsx") quote per-token
  if (fs.existsSync(bundledCli)) {
    runner = ["node"];
    cliPath = bundledCli;
  } else {
    cliPath = path.resolve(here, "../cli/index.ts");
    const projectRoot = path.resolve(here, "../.."); // .../Workora
    const tsxBin = path.join(projectRoot, "node_modules", ".bin", "tsx");
    runner = fs.existsSync(tsxBin) ? [tsxBin] : ["npx", "tsx"]; // prefer local tsx, fallback to npx
  }

  const q = (s: string) => JSON.stringify(s); // safe quoting for both sh and cmd.exe
  const invocation = [...runner, cliPath].map(q).join(" ");
  const wrapper = path.join(dir, "Workora");
  const sh = `#!/bin/sh\n# Workora agent CLI wrapper (auto-generated by daemon)\nexec ${invocation} "$@"\n`;
  fs.writeFileSync(wrapper, sh);
  fs.chmodSync(wrapper, 0o755);

  if (process.platform === "win32") {
    const cmdWrapper = path.join(dir, "Workora.cmd");
    const cmdContent = `@echo off\r\nREM Workora agent CLI wrapper (auto-generated by daemon)\r\n${invocation} %*\r\n`;
    fs.writeFileSync(cmdWrapper, cmdContent);
  }

  return dir;
}
